version: '3.8'

services:
  # Production Frontend
  prod-frontend:
    build: ./frontend
    ports:
      - "3000:3000"  # Standard production port
    depends_on:
      - shared-backend
    environment:
      VITE_API_URL: https://xai.eastus.cloudapp.azure.com
    restart: unless-stopped
    networks:
      - shared-network
      - prod-network

  # Production Nginx (Main Production)
  prod-nginx:
    image: nginx:alpine
    ports:
      - "80:80"   # Standard HTTP port
      - "443:443" # Standard HTTPS port
    volumes:
      - ./nginx.prod.shared.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - shared-backend
      - prod-frontend
    command: nginx -g 'daemon off;'
    restart: unless-stopped
    networks:
      - shared-network
      - prod-network

  # Production Certbot
  prod-certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: /bin/sh
    command: -c "trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew --quiet; done"
    restart: unless-stopped
    networks:
      - shared-network
      - prod-network

networks:
  shared-network:
    external: true
  prod-network:
    driver: bridge

